languageCode = "en"
languageName = "English"
weight = 1
title = "Bioinformatics FRiday"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Promote training and growth in bioinformatics through free courses for all interested community."
logo = "Fiver.png"

[author]
name = "Jorge Alfredo Suazo Victoria"
image = "LogoAutor.png"
headline = "Genomic Science Student"
bio = "I made this web page :)"
links = [ { github = "https://github.com/3LCONEJO" } ]
