colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "posts" ]
defaultBackgroundImage = "HCK.gif"
defaultFeaturedImage = "fitur.png"
highlightCurrentMenuArea = true

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "card"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = false
homepageImage = "Yoymin.jpeg"

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]
layoutBackgroundBlur = true

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]

[term]
groupByYear = ""
